### ISSUE TITLE
release: automatically generate release announce in brog from release note 

### ISSUE THREAD

**Issue by otegami** [groonga/groonga#2114]
### What is your problem?

Currently, when releasing a new version, we have to manually create a blog post to announce it. This process is redundant and time-consuming because we already have detailed release notes that cover the changes in the new version.

## Proposed Solution:

Implement a Rake task that automatically generates a blog post from the existing release notes.
This will streamline the release process and reduce the manual effort required during releases.

**Comment by otegami** [comment]
**Image how we want to call this rake task**

```console
$ rake release:blog:announce:generate (...arguments)
```

**TODO**
- [ ] Implement a rake task to generate blog without contents
  - [ ] Implement only interface of the rake tesk
  - [ ] Implement the logic of the rake task
- [ ] Write the blog content

**Comment by kou** [comment]
Moved to https://github.com/groonga/groonga.org/issues/83 .
